services:
  app:
    build: .
    ports:
      - '5173:3000'
    environment:
      - NODE_ENV=production
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - ORIGIN=${ORIGIN:-http://localhost:5173}
    restart: unless-stopped
